apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vote-network-policy
  namespace: vote
spec:
  podSelector:
    matchLabels:
      app: azure-vote-front
  policyTypes: 
   - Ingress
  ingress:
    - from:
       - namespaceSelector:
           matchLabels:
            kubernetes.io/metadata.name: vote
       - ipBlock:
           cidr: 0.0.0.0/0
           except:
             - 10.0.0.0/16
             - 10.244.0.0/16
      ports:
        - protocol: TCP
          port: 80
