apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vote-network-policy
  namespace: vote
spec:
  podSelector:
    matchLabels:
      app: azure-vote-front
  policyTypes: Ingress
  ingress:
    from:
      namespaceSelector:
        matchLabels:
          name: vote
