name: Docker Image CI

on:
  workflow_dispatch:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: standardsimg.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t standardsimg.azurecr.io/testGithub:${{ github.sha }}
        docker push standardsimg.azurecr.io/testGithub:${{ github.sha }}
